import pyglet

WINDOW_WIDTH = 1080
WINDOW_HEIGHT = 720
BOTTOM_BORDER = 60

DANGER_RADIUS = 10000
COLLISION_ENTRY = 10

WEAPON_VERT = 60
CHARACTER_VERT = 50


BOMB_IMAGE = pyglet.resource.image("w1.png")
BOMB_WIDTH = 15
BOMB_HEIGHT = 15

'''
THESE CHANGE IF SCREEN DIMENSIONS CHANGE
'''
BOMB_X = WINDOW_WIDTH/2-BOMB_WIDTH/2-26
BOMB_Y = 97
